import Link from "next/link";
import { ArrowLeft, CircleHelp, Copy, ShieldCheck } from "lucide-react";
import { BottomNav } from "@/components/layout/bottom-nav";
import { Button } from "@/components/ui/button";

export default async function TraderProfilePage({ params }: { params: Promise<{ traderId: string }> }) {
  const { traderId } = await params;
  return <main className="min-h-dvh bg-background pb-24 text-foreground lg:pb-8"><header className="border-b border-card-border bg-card/70"><div className="mx-auto max-w-4xl px-4 py-5 sm:px-6"><Link href="/more/leaderboard" className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.2em] text-muted"><ArrowLeft className="size-3" />Back to leaderboard</Link><div className="mt-5 flex flex-wrap items-end justify-between gap-4"><div><p className="flex items-center gap-2 text-xs text-primary"><ShieldCheck className="size-4" />Trader profile</p><h1 className="mt-2 text-3xl font-semibold">{traderId}</h1><p className="mt-2 text-sm text-muted">Verified history, risk context, and copy controls.</p></div><Link href={`/more/copy-trade?trader=${traderId}`} className="inline-flex h-9 items-center justify-center gap-2 rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground"><Copy className="size-4" />Copy trader</Link></div></div></header><div className="mx-auto flex max-w-4xl flex-col gap-5 px-4 py-5 sm:px-6"><section className="grid gap-px overflow-hidden rounded-xl border border-card-border bg-card-border sm:grid-cols-4">{["Verified ROI", "Realized PnL", "Win rate", "Sample size"].map((label) => <div key={label} className="bg-card p-4"><p className="text-[10px] uppercase tracking-wider text-muted">{label}</p><p className="mt-3 font-mono text-xl">—</p></div>)}</section><section className="rounded-xl border border-card-border bg-card p-6"><CircleHelp className="size-6 text-muted" /><h2 className="mt-4 text-lg font-semibold">Profile data unavailable</h2><p className="mt-2 max-w-lg text-sm leading-6 text-muted">The verified trader index is not connected yet. No ROI, PnL, positions, follower count, token identity, or risk score is shown until it can be sourced from verified activity.</p></section></div><BottomNav /></main>;
}
