"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { BottomNav } from "@/components/layout/bottom-nav";
import { Button } from "@/components/ui/button";
import { Metric, Panel, PanelHeading, PumpMark, SectionBanner, StatusDot, TokenAvatar } from "@/components/brand/pump-mark";

interface WalletView { id:string; name:string; publicKey:string; isPrimary:boolean; balanceSol?:number|null }

export default function HomePage() {
  const [wallets,setWallets]=useState<WalletView[]>([]); const [loading,setLoading]=useState(true); const [creating,setCreating]=useState(false); const [error,setError]=useState<string|null>(null);
  const load=useCallback(async()=>{setLoading(true);try{const res=await fetch("/api/wallets");const data=await res.json();if(res.ok)setWallets(data.wallets||[]);else setError(data.error||"Could not load wallets")}catch{setError("Network error loading wallets")}finally{setLoading(false)}},[]);
  useEffect(()=>{load()},[load]);
  const createWallet=async()=>{setCreating(true);setError(null);try{const res=await fetch("/api/wallets",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:"Main"})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Create failed");await load()}catch(e){setError(e instanceof Error?e.message:"Create failed")}finally{setCreating(false)}};
  const primary=wallets.find(w=>w.isPrimary)||wallets[0]; const balance=primary?.balanceSol; const funded=balance!=null&&balance>.01; const hasWallet=wallets.length>0;
  return <main className="terminal-content min-h-dvh"><header className="flex items-center justify-between border-b border-border px-4 py-4 sm:px-6"><PumpMark compact/><StatusDot label="mainnet"/></header><SectionBanner eyebrow="command center / 01" title="Fund. Hunt. Trade." detail="An execution layer for on-chain opportunity."/><div className="mx-auto flex w-full max-w-5xl flex-col gap-4 p-4 sm:p-6">{error&&<div role="alert" className="border border-danger/40 bg-danger/10 px-4 py-3 text-xs text-danger">{error}</div>}
    <Panel><PanelHeading eyebrow="capital layer" title="Wallet overview" action={<StatusDot label={hasWallet?"connected":"not configured"} tone={hasWallet?"primary":"warning"}/>} /><div className="grid grid-cols-3"><Metric label="wallet" value={primary?`${primary.publicKey.slice(0,4)}…${primary.publicKey.slice(-4)}`:"—"}/><Metric label="balance" value={balance!=null?`${balance.toFixed(4)} SOL`:"—"} tone="primary"/><Metric label="status" value={funded?"FUNDED":"AWAITING"} tone={funded?"primary":"warning"}/></div><div className="px-4 py-4">{loading?<p className="text-xs text-muted-foreground">Syncing wallet from RPC…</p>:!hasWallet?<><p className="max-w-md text-xs leading-5 text-muted-foreground">Create an encrypted trading wallet. Private keys never leave the server encrypted store.</p><Button className="mt-4" onClick={createWallet} disabled={creating}>{creating?"Creating…":"Create wallet"}</Button></>:<><p className="font-mono text-[10px] text-muted-foreground">{primary?.publicKey}</p>{!funded&&<p className="mt-2 text-xs text-warning">Send SOL to this address to fund. Balances are live from RPC — never simulated.</p>}</>}</div></Panel>
    <Panel><PanelHeading eyebrow="system status" title="Auto-Hunter" action={<StatusDot label="offline" tone="warning"/>}/><div className="px-4 py-5"><div className="flex items-baseline justify-between"><div><p className="font-mono text-2xl font-semibold text-foreground">0 <span className="text-sm font-normal text-muted-foreground">tokens scanned</span></p><p className="mt-2 text-xs text-muted-foreground">The opportunity engine activates after wallet funding.</p></div><Link href="/terminal"><Button variant="secondary" size="sm">Open terminal</Button></Link></div><div className="mt-5 grid grid-cols-3 border border-border"><Metric label="score ≥" value="75"/><Metric label="liquidity ≥" value="$50k"/><Metric label="risk" value="LOW" tone="primary"/></div></div></Panel>
    <div className="grid gap-4 md:grid-cols-2"><Panel><PanelHeading eyebrow="market pulse" title="SOL / USD" action={<StatusDot label="live"/>}/><div className="flex items-end justify-between px-4 py-5"><span className="font-mono text-2xl">—</span><span className="text-xs text-muted-foreground">provider unavailable</span></div></Panel><Panel><PanelHeading eyebrow="next route" title="Choose a strategy"/><div className="flex flex-col gap-2 p-4"><Link href="/terminal" className="border border-border px-3 py-3 transition-colors hover:border-primary/60"><span className="block text-sm font-medium">Auto-Hunter</span><span className="mt-1 block text-xs text-muted-foreground">Scan, filter, enter, monitor automatically.</span></Link><Link href="/more/smart-devs" className="border border-border px-3 py-3 transition-colors hover:border-primary/60"><span className="block text-sm font-medium">Smart Dev Follow</span><span className="mt-1 block text-xs text-muted-foreground">Track proven developers with risk gates.</span></Link></div></Panel></div>
    <Panel><PanelHeading eyebrow="activity stream" title="Recent activity"/><div className="flex flex-col gap-3 px-4 py-4 text-xs text-muted-foreground"><p><span className="mr-2 text-primary">✓</span>Risk engine ready</p><p><span className="mr-2 text-primary">✓</span>Wallet state synchronized</p><p><span className="mr-2 text-warning">○</span>Awaiting funded wallet</p></div></Panel>
  </div><BottomNav/></main>
}
